### ISSUE TITLE
Allow events on Dashboard to be RSVP'd to in order to have capacity-limited events

### ISSUE THREAD

**Issue by jwoglom** [hackumass/dashboard#110]
We need functionality for people to be able to RSVP to certain events on the day of. This can be accomplished as part of the events calendar in dashboard. We should allow you to as an admin set an event as requiring rsvps. And then if an event requires it, you can press a button to RSVP and we save your user in a list of RSVPd users. Then we need to make an equivalent system to check in for "event check in", where the admin has a page open and you enter the person's email and they get marked in the db as having attended the event, so that the event check in can happen at the door for a workshop or talk. This will especially be needed for, eg., a workshop where there can only be a certain number of people max.

**Comment by EvanFellman** [comment]
Finished
